version: "3.7"
services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: pass1234
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
volumes:
  postgres_data: