# Generated by Django 3.2.5 on 2021-07-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторы',
            },
        ),
        migrations.CreateModel(
            name='T_Procedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_type', models.CharField(max_length=100)),
                ('purchaseNumber', models.IntegerField()),
                ('docPublishDate', models.DateTimeField()),
                ('purchaseObjectInfo', models.TextField(max_length=5000)),
                ('regNum', models.IntegerField()),
                ('maxPrice', models.IntegerField()),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.t_users')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
                'ordering': ('id',),
            },
        ),
    ]
